import type { Metadata } from "next";
import "../assets/globals.css";
import { Anuphan } from "@next/font/google";

const anuphan = Anuphan({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${anuphan.className}`}>
        {children}
      </body>
    </html>
  );
}
